baseURL = 'https://linn.today/'
languageCode = 'en-us'
title = 'Linn Today'
theme = 'PaperMod'

[params]
    env = 'production'
    title = 'The Unbreakable Entrepreneur'
    description = 'Building Revenue in a Crisis Economy'
    author = 'Sai Han Linn'
    
    # Social Icons (Authority Signals)
    [[params.socialIcons]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/saihanlinn/"
    [[params.socialIcons]]
        name = "facebook"
        url = "https://www.facebook.com/saihanlinn/"
    [[params.socialIcons]]
        name = "twitter"
        url = "https://x.com/saihanlinn"

    [params.profileMode]
        enabled = true
        title = "Sai Han Linn"
        subtitle = "The Unbreakable Entrepreneur: Building Revenue in a Crisis Economy."
        imageUrl = "" # I can help you host your headshot later
        
        # Primary Action Buttons
        [[params.profileMode.buttons]]
            name = "Read the Memoirs"
            url = "/posts"
        [[params.profileMode.buttons]]
            name = "Join the Substack"
            url = "https://saihanlinn.substack.com/"
        [[params.profileMode.buttons]]
            name = "Linn International"
            url = "https://primer.linn.services/"
        [[params.profileMode.buttons]]
            name = "Nature's Art Lab"
            url = "https://natures.linn.services/"

    [params.label]
        text = "LINN.TODAY"

[menu]
    [[menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/posts/"
        weight = 10
    [[menu.main]]
        identifier = "substack"
        name = "Newsletter"
        url = "https://saihanlinn.substack.com/"
        weight = 20
